import Head from 'next/head'
import Image from 'next/image'
import Files from '../components/Files'
import Header from '../components/Header'
import Start from '../components/Start'
import {auth, db} from '../firebase'
import Login from '../components/Login'
import { useAuthState } from 'react-firebase-hooks/auth'
import { useState } from 'react'
import { Box, Button, Input, Modal, TextField, Typography } from '@mui/material'
import { isMobile } from 'react-device-detect'
 
const style = {
  position: 'absolute',
  top: '50%',
  left: '50%',
  transform: 'translate(-50%, -50%)',
  borderRadius:"10px",
  width: isMobile?300:400,
  bgcolor: 'background.paper',
  boxShadow: 24,
  p: 4,
};


export default function Home() {
  const [user] = useAuthState(auth)
  const [open, setOpen] = useState(false);
  const handleOpen = () => setOpen(true);
  const handleClose = () => setOpen(false);
  if(!user) return <Login />



  return (
    <div >
      <Head>
        <title>DocWizard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/5968/5968517.png" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>


      <Header />
      <Start openNew={handleOpen} />
      <Files />
      <Modal
        open={open}
        onClose={handleClose}
        aria-labelledby="modal-modal-title"
        aria-describedby="modal-modal-description"
      >
        <Box sx={style}>
          <Typography id="modal-modal-title" variant="h6" component="h2">
            Start a new document
          </Typography>
          <div className='mt-5 w-full'>
            <TextField label="Enter file name" className='w-full' color="primary" placeholder='File name' />
          </div>

          <div className='flex items-end justify-end mt-5'>
            <Button>
              Create
            </Button>

            <Button onClick={handleClose} color='error'>
              Cancel
            </Button>
          </div>
        </Box>
      </Modal>
    </div>
  )
}
