import Head from 'next/head'
import Image from 'next/image'
import Files from '../components/Files'
import Header from '../components/Header'
import Start from '../components/Start'
import {db} from '../firebase'
export default function Home() {

  return (
    <div >
      <Head>
        <title>DocWizard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/5968/5968517.png" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>


      <Header />
      <Start />
      <Files />
    </div>
  )
}
